version: '3.7'
services:
    ui:
        image: joxit/docker-registry-ui:1.5-static
        environment:
            - DELETE_IMAGES=true
            - REGISTRY_TITLE=Private Docker Registry
            - REGISTRY_URL=http://registry:5000
            - SINGLE_REGISTRY=true
        networks:
            - traefik-public
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.hub-http.rule=Host(`hub.herman.team`)
                - traefik.http.routers.hub-http.entrypoints=http
                - traefik.http.routers.hub-http.middlewares=https-redirect
                - traefik.http.routers.hub-https.rule=Host(`hub.herman.team`)
                - traefik.http.routers.hub-https.entrypoints=https
                - traefik.http.routers.hub-https.tls=true
                - traefik.http.routers.hub-https.tls.certresolver=le
                - traefik.http.services.hub.loadbalancer.server.port=80

    registry:
        image: registry:2.8
        environment:
            - REGISTRY_STORAGE_DELETE_ENABLED=true
        volumes:
            - registry:/var/lib/registry
            - ./registry-config/credentials.yml:/etc/docker/registry/config.yml
            - ./registry-config/htpasswd:/etc/docker/registry/htpasswd
        networks:
            - traefik-public
        deploy:
            placement:
                constraints:
                - node.labels.registry.registry == true


    cache-registry:
        image: registry:2.8
        environment:
            REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
            REGISTRY_STORAGE_DELETE_ENABLED: 1
        volumes:
            - cache-registry:/var/lib/registry
        networks:
            - traefik-public
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.cache-hub-http.rule=Host(`cache-hub.herman.team`)
                - traefik.http.routers.cache-hub-http.entrypoints=http
                - traefik.http.routers.cache-hub-http.middlewares=https-redirect
                - traefik.http.routers.cache-hub-https.rule=Host(`cache-hub.herman.team`)
                - traefik.http.routers.cache-hub-https.entrypoints=https
                - traefik.http.routers.cache-hub-https.tls=true
                - traefik.http.routers.cache-hub-https.tls.certresolver=le
                - traefik.http.services.cache-hub.loadbalancer.server.port=5000
            placement:
                constraints:
                - node.labels.registry.cache-registry == true

volumes:
    registry:
    cache-registry:
    traefik-public-certs:

networks:
    traefik-public:
        external: true
