server:
	ansible-playbook server.yml -i hosts.yml

authorize:
	ansible-playbook authorize.yml -i hosts.yml

upgrade:
	ansible-playbook upgrade.yml -i hosts.yml

docker-login:
	ansible-playbook -i hosts.yml docker-login.yml
